
language_code = {'English': 10,
                 'Dutch': 11,
                 'French': 12,
                 'German': 13,
                 'Italian': 14,
                 'Polish': 15,
                 'Portuguese': 16,
                 'Spanish': 17,
                 'Danish': 18,
                 'Northern Conchucos Ancash Quechua': 50,
                 'Cajonos Zapotec': 51,
                 'Choapan Zapotec': 52,
                 'Maltese': 53,
                 'Kamba (Kenya)': 54,
                 'Highland Popoluca': 55,
                 'Caquinte': 56,
                 'Marathi': 57,
                 'Guerrero Nahuatl': 58,
                 'Gapapaiwa': 59,
                 'Atatláhuca Mixtec': 60,
                 'Hindi': 61,
                 'Cebuano': 62,
                 'Nopala Chatino': 63,
                 'Coatecas Altas Zapotec': 64,
                 "Kwara'ae": 65,
                 'Sarangani Blaan': 66,
                 'Mankanya': 67,
                 'Pinotepa Nacional Mixtec': 68,
                 'Pele-Ata': 69,
                 'Binumarien': 70,
                 'Luang': 71,
                 'Peñoles Mixtec': 72,
                 'Japanese': 73,
                 'Tepetotutla Chinantec': 74,
                 'Candoshi-Shapra': 75,
                 'Huamalíes-Dos de Mayo Huánuco Quechua': 76,
                 'Wala': 77,
                 'North Tanna': 78,
                 'Ozumacín Chinantec': 79,
                 'Eastern Huasteca Nahuatl': 80,
                 'Caribbean Javanese': 81,
                 'Swahili (macrolanguage)': 82,
                 'Alune': 83,
                 'Bengali': 84,
                 'Northern Emberá': 85,
                 'Armenian': 86,
                 'Luguru': 87,
                 'Tagalog': 88,
                 'Somba-Siawari': 89,
                 'Tsikimba': 90,
                 'Kouya': 91,
                 'Shuar': 92,
                 'Dhao': 93,
                 'San Blas Kuna': 94,
                 'Matu Chin': 95,
                 'Northern Oaxaca Nahuatl': 96,
                 'Tlicho': 97,
                 'Keyagana': 98,
                 'Agutaynen': 99,
                 'Bwanabwana': 100,
                 'Umbu-Ungu': 101,
                 'Thado Chin': 102,
                 'Cacua': 103,
                 'Ocotepec Mixtec': 104,
                 'Yawa': 105,
                 'Mengen': 106,
                 'Uspanteco': 108,
                 'Nadëb': 109,
                 'Eastern Maroon Creole': 110,
                 'Khmer': 111,
                 'Melpa': 112,
                 'Cashinahua': 113,
                 'Jamiltepec Mixtec': 114,
                 'Comaltepec Chinantec': 115,
                 'Yalunka': 116,
                 'Nomatsiguenga': 117,
                 'Chortí': 118,
                 'Kankanaey': 119,
                 'Georgian': 120,
                 'Migabac': 121,
                 'Totontepec Mixe': 122,
                 'Mongolian': 123,
                 'Uzbek': 124,
                 'Mangseng': 125,
                 'Maca': 126,
                 'Gujarati': 127,
                 'Yaouré': 128,
                 'Cofán': 129,
                 'Baruga': 130,
                 'Mandarin Chinese': 131,
                 'Akoose': 132,
                 'Obo Manobo': 133,
                 'Epena': 134,
                 'Ngangam': 135,
                 'Mag-antsi Ayta': 136,
                 'Parecís': 137,
                 'Guajajára': 138,
                 'Tacana': 139,
                 'Dawro': 140,
                 'Limbu': 141,
                 'Luo (Kenya and Tanzania)': 142,
                 'Mixtepec Zapotec': 143,
                 'Nepali (macrolanguage)': 144,
                 'Mezquital Otomi': 145,
                 'Huaylla Wanca Quechua': 146,
                 'Noone': 147,
                 'Thai': 148,
                 'Merey': 149,
                 'Bokobaru': 150,
                 'Urat': 151,
                 'Ocotlán Zapotec': 152,
                 'Busa': 153,
                 'Eastern Khumi Chin': 154,
                 'Zulu': 155,
                 'Quioquitani-Quierí Zapotec': 156,
                 'Russian': 157,
                 'Magdalena Peñasco Mixtec': 158,
                 'Paranan': 159,
                 'Lalana Chinantec': 160,
                 'Guarayu': 161,
                 'Coyutla Totonac': 162,
                 'Uduk': 163,
                 'South Bolivian Quechua': 164,
                 'Aguaruna': 165,
                 'Hebrew': 166,
                 'Hamer-Banna': 167,
                 'Huli': 168,
                 'Xhosa': 169,
                 'North Junín Quechua': 170,
                 'Occitan (post 1500)': 171,
                 'Arop-Lokep': 172,
                 'Makaa': 173,
                 'Southern Nambikuára': 174,
                 'Chayahuita': 175,
                 'Galibi Carib': 176,
                 'Texmelucan Zapotec': 178,
                 'Malay (macrolanguage)': 179,
                 'Matigsalug Manobo': 180,
                 'Hdi': 181,
                 'Siona': 182,
                 'Wolof': 183,
                 'Tuyuca': 184,
                 'Lealao Chinantec': 185,
                 'Slovenian': 186,
                 'Highland Totonac': 187,
                 'Kisar': 188,
                 'Lukpa': 189,
                 'Bora': 191,
                 'Persian': 192,
                 'Aruamu': 193,
                 'Croatian': 194,
                 'Tereno': 195,
                 'Akawaio': 196,
                 'Lachixío Zapotec': 197,
                 'Santo Domingo Albarradas Zapotec': 198,
                 'Czech': 199,
                 'Zigula': 200,
                 'Gwahatike': 201,
                 'Palantla Chinantec': 202,
                 'Tamil': 203,
                 'Zyphe Chin': 204,
                 'Garifuna': 205,
                 'Kamano': 206,
                 'Bosnian': 207,
                 'Mokole': 208,
                 'Tlachichilco Tepehua': 209,
                 'Miahuatlán Zapotec': 210,
                 'Turkish': 211,
                 'Saint Lucian Creole French': 212,
                 'Oromo': 213,
                 'Tektiteko': 214,
                 'Fulah': 215,
                 'Burmese': 216,
                 'Cuiba': 217,
                 'Sena': 218,
                 'Tabasco Chontal': 219,
                 'Imbongu': 220,
                 'Bedjond': 221,
                 'Sochiapam Chinantec': 222,
                 'Guayabero': 224,
                 'Afrikaans': 225,
                 'Ramoaaina': 226,
                 'Amatlán Zapotec': 227,
                 'Roviana': 228,
                 'Swahili (individual language)': 229,
                 'Chayuco Mixtec': 230,
                 'Murui Huitoto': 231,
                 'Tangoa': 232,
                 'Belize Kriol English': 234,
                 'Kuman (Papua New Guinea)': 235,
                 'Central Mazahua': 236,
                 'Azerbaijani': 237,
                 'Yakan': 238,
                 'Baruya': 239,
                 'Tezoatlán Mixtec': 240,
                 'Suba': 241,
                 'Kenga': 242,
                 'Ika': 243,
                 'Francisco León Zoque': 244,
                 'Ringgou': 245,
                 'Bulgarian': 246,
                 'Kriol': 247,
                 'Borong': 248,
                 'Mapos Buang': 249,
                 'Cajamarca Quechua': 250,
                 'Coatlán Mixe': 251,
                 'Luxembourgish': 252,
                 'Yalálag Zapotec': 253,
                 'Ndamba': 254,
                 'Misima-Panaeati': 255,
                 'Buglere': 256,
                 'Assamese': 257,
                 'Ngäbere': 258,
                 'Ganda': 259,
                 'Lacandon': 260,
                 'Tol': 261,
                 'Inga': 262,
                 'Boko (Benin)': 263,
                 'Machiguenga': 264,
                 'Ashéninka Pajonal': 265,
                 'Takia': 266,
                 'Chol': 267,
                 'Awa (Papua New Guinea)': 268,
                 'Urarina': 269,
                 'Central Tunebo': 270,
                 'Zacatlán-Ahuacatlán-Tepetzintla Nahuatl': 271,
                 'Iyo': 272,
                 'Chiquitano': 273,
                 'Ucayali-Yurúa Ashéninka': 274,
                 'Koronadal Blaan': 275,
                 'Nkonya': 276,
                 'Susu': 277,
                 'Yosondúa Mixtec': 278,
                 'Lowland Tarahumara': 279,
                 'Yoruba': 280,
                 'Mamara Senoufo': 281,
                 'Southeastern Tepehuan': 282,
                 'Eastern Tamang': 284,
                 'Yine': 285,
                 'Sranan Tongo': 286,
                 'Fataleka': 287,
                 'Western Bukidnon Manobo': 288,
                 'Yagua': 289,
                 'Guambiano': 290,
                 'Dedua': 291,
                 'Pichis Ashéninka': 292,
                 'North Tairora': 293,
                 'Male (Ethiopia)': 294,
                 'Western Huasteca Nahuatl': 295,
                 'Ozolotepec Zapotec': 296,
                 'Kayabí': 297,
                 'Tok Pisin': 298,
                 'Secoya': 299,
                 'Ipili': 300,
                 'Kagayanen': 301,
                 'Ancient Greek (to 1453)': 302,
                 'Sharanahua': 303,
                 'Wapishana': 304,
                 'Iloko': 305,
                 'Irish': 306,
                 'Gamo': 307,
                 'Carapana': 308,
                 'Capanahua': 309,
                 'Woun Meu': 310,
                 'Korean': 311,
                 'Supyire Senoufo': 312,
                 'Northern Paiute': 313,
                 'Southwestern Dinka': 314,
                 'Binukid': 315,
                 'Swedish': 316,
                 'Vidunda': 317,
                 'Catalan': 318,
                 'Zaiwa': 319,
                 'Maskelynes': 320,
                 'Yue Chinese': 321,
                 'Bola': 322,
                 'Ayautla Mazatec': 323,
                 'Northern Puebla Nahuatl': 324,
                 'Ese': 325,
                 'Achi': 326,
                 'South Azerbaijani': 327,
                 'Ninzo': 328,
                 'Sierra de Juárez Zapotec': 329,
                 'Eastern Apurímac Quechua': 330,
                 'Muyang': 331,
                 'Mitla Zapotec': 332,
                 'Shona': 333,
                 'Finnish': 334,
                 'Ewe': 335,
                 'Teribe': 336,
                 'Yatee Zapotec': 337,
                 'Torres Strait Creole': 338,
                 'Kupang Malay': 339,
                 'Naasioi': 340,
                 'Javanese': 341,
                 'Akan': 342,
                 'Southeastern Puebla Nahuatl': 343,
                 'Macuna': 344,
                 'Usila Chinantec': 345,
                 'Agarabi': 347,
                 'Kutu': 348,
                 "Sa'a": 349,
                 'Tii': 350,
                 'Tatuyo': 351,
                 'Slovak': 352,
                 'Ese Ejja': 353,
                 'Waima': 354,
                 "Popti'": 355,
                 'Muinane': 356,
                 'Asháninka': 357,
                 'San Marcos Tlacoyalco Popoloca': 358,
                 'Angor': 359,
                 'Lao': 360,
                 'Michoacán Nahuatl': 361,
                 'Tajik': 362,
                 'Arabela': 363,
                 'Amharic': 364,
                 'Romanian': 365,
                 'Colorado': 366,
                 'Sindhi': 367,
                 'Chumburung': 368,
                 'Kwamera': 369,
                 'Huallaga Huánuco Quechua': 370,
                 'Telugu': 371,
                 'Malayalam': 372,
                 'Uripiv-Wala-Rano-Atchin': 373,
                 'Balantak': 374,
                 'Ngindo': 375,
                 'Tucano': 376,
                 'Whitesands': 377,
                 'Gourmanchéma': 378,
                 'Kikuyu': 379,
                 'Kinga': 380,
                 'Panjabi': 381,
                 'Achuar-Shiwiar': 382,
                 'Kire': 383,
                 'Tboli': 384,
                 'Kannada': 385,
                 'Cerma': 386,
                 'Piratapuyo': 387,
                 'Arosi': 388,
                 'Kenyang': 389,
                 'Kanite': 390,
                 'Galician': 391,
                 'Kwere': 392,
                 'Malay (individual language)': 393,
                 "Yanesha'": 394,
                 'Copala Triqui': 395,
                 'Southern Conchucos Ancash Quechua': 396,
                 'Gela': 397,
                 'Awa-Cuaiquer': 398,
                 'Urdu': 399,
                 'Macushi': 400,
                 'Waimaha': 401,
                 'Huambisa': 402,
                 'Serbian': 403,
                 'Pedi': 404,
                 'Asturian': 405,
                 'Saramaccan': 406,
                 'Makonde': 407,
                 'Macedonian': 408,
                 'Mopán Maya': 409,
                 'Pogolo': 410,
                 'Yaminahua': 411,
                 'Central Kurdish': 412,
                 'Somali': 413,
                 'Sudest': 414,
                 'Lambayeque Quechua': 415,
                 'Siriano': 416,
                 'Border Kuna': 417,
                 "Tohono O'odham": 418,
                 'Ivbie North-Okpela-Arhe': 419,
                 'Lole': 420,
                 'Siane': 421,
                 'Norwegian Bokmål': 422,
                 'South Tairora': 423,
                 'Modern Greek (1453-)': 424,
                 'Kirghiz': 425,
                 'Yatzachi Zapotec': 426,
                 'Chachi': 427,
                 'Northern Pastaza Quichua': 428,
                 'Tuma-Irumu': 429,
                 'Chiquihuitlán Mazatec': 430,
                 'Diuxi-Tilantongo Mixtec': 431,
                 'Welsh': 432,
                 'Juquila Mixe': 433,
                 'Mato': 434,
                 'Chipaya': 435,
                 'Highland Puebla Nahuatl': 436,
                 'Umbundu': 437,
                 'Buamu': 438,
                 'Central Huasteca Nahuatl': 439,
                 'Ignaciano': 440,
                 'Huehuetla Tepehua': 441,
                 'Gwichʼin': 442,
                 'Ticuna': 443,
                 'Dangaléat': 444,
                 'Barai': 445,
                 'Mwani': 446,
                 'Kekchí': 447,
                 'Guanano': 448,
                 'Latin': 449,
                 'Pitjantjatjara': 451,
                 'Tewa (USA)': 452,
                 'Oriya (macrolanguage)': 453,
                 'Lingala': 454,
                 'Lewo': 455,
                 'North Bolivian Quechua': 456,
                 'Kazakh': 457,
                 'Indonesian': 458,
                 'San Pedro Amuzgos Amuzgo': 459,
                 'Maori': 460,
                 'Ditammari': 461,
                 'Rincón Zapotec': 462,
                 'Sabaot': 463,
                 'Southern Puebla Mixtec': 464,
                 'Cashibo-Cacataibo': 465,
                 'Odia': 466,
                 'Hungarian': 467,
                 'Shipibo-Conibo': 468,
                 'Belarusian': 469,
                 'Ambai': 470,
                 'Filipino': 471,
                 'San Mateo Del Mar Huave': 472,
                 'Huaylas Ancash Quechua': 473,
                 'Pushto': 474,
                 'Igbo': 475,
                 'Isthmus Zapotec': 476,
                 'Haitian': 477,
                 'Borei': 478,
                 'Ngulu': 479,
                 'Yucuna': 480,
                 'Ukrainian': 481,
                 'Aguacateco': 483,
                 'Sabu': 484,
                 'Querétaro Otomi': 485,
                 'Nyindrou': 486,
                 'Sunwar': 487,
                 'Bughotu': 488,
                 'Jalapa De Díaz Mazatec': 489,
                 'Nyanja': 490,
                 'Minica Huitoto': 491,
                 'Kyaka': 492,
                 'Gilaki': 493,
                 'Kabuverdianu': 494,
                 'Mamasa': 495,
                 'Margos-Yarowilca-Lauricocha Quechua': 496,
                 'Paumarí': 497,
                 'Western Kanjobal': 498,
                 'Molima': 499,
                 'Estonian': 500,
                 'El Nayar Cora': 501,
                 'San Martín Quechua': 502,
                 'Lithuanian': 503,
                 'Caribbean Hindustani': 504,
                 'Coatzospan Mixtec': 505,
                 'Arabic': 506,
                 'Panao Huánuco Quechua': 507,
                 'Guahibo': 508,
                 'Kandawo': 509,
                 'Hausa': 510,
                 'Western Tlacolula Valley Zapotec': 511,
                 'Makhuwa-Meetto': 512,
                 'Konkomba': 513,
                 'Kwaio': 514,
                 'Urubú-Kaapor': 515,
                 'Kayapó': 516,
                 'Bambam': 517,
                 'Miyobe': 518,
                 'Vietnamese': 519,
                 'Latvian': 520,
                 'Mbuko': 521,
                 'Baatonum': 522,
                 'Anjam': 523,
                 'Icelandic': 524}

mls_language_map = {'dutch': 'Dutch',
                    'french': 'French',
                    'german': 'German',
                    'italian': 'Italian',
                    'polish': 'Polish',
                    'portuguese': 'Portuguese',
                    'spanish': 'Spanish',
                    'danish': 'Danish'}

fleurs_language_map = {'ceb_ph': 'Cebuano',
                       'gl_es': 'Galician',
                       'tr_tr': 'Turkish',
                       'pl_pl': 'Polish',
                       'nso_za': 'Pedi',
                       'sn_zw': 'Shona',
                       'pt_br': 'Portuguese',
                       'kn_in': 'Kannada',
                       'lg_ug': 'Ganda',
                       'ko_kr': 'Korean',
                       'xh_za': 'Xhosa',
                       'ml_in': 'Malayalam',
                       'it_it': 'Italian',
                       'mi_nz': 'Maori',
                       'lv_lv': 'Latvian',
                       'af_za': 'Afrikaans',
                       'ru_ru': 'Russian',
                       'wo_sn': 'Wolof',
                       'te_in': 'Telugu',
                       'as_in': 'Assamese',
                       'cy_gb': 'Welsh',
                       'oc_fr': 'Occitan (post 1500)',
                       'my_mm': 'Burmese',
                       'or_in': 'Oriya (macrolanguage)',
                       'hi_in': 'Hindi',
                       'ro_ro': 'Romanian',
                       'hr_hr': 'Croatian',
                       'sd_in': 'Sindhi',
                       'sr_rs': 'Serbian',
                       'tg_tj': 'Tajik',
                       'lt_lt': 'Lithuanian',
                       'en_us': 'English',
                       'da_dk': 'Danish',
                       'sl_si': 'Slovenian',
                       'lb_lu': 'Luxembourgish',
                       'bg_bg': 'Bulgarian',
                       'hy_am': 'Armenian',
                       'fr_fr': 'French',
                       'ig_ng': 'Igbo',
                       'am_et': 'Amharic',
                       'sk_sk': 'Slovak',
                       'luo_ke': 'Luo (Kenya and Tanzania)',
                       'kk_kz': 'Kazakh',
                       'yue_hant_hk': 'Yue Chinese',
                       'ar_eg': 'Arabic',
                       'jv_id': 'Javanese',
                       'ckb_iq': 'Central Kurdish',
                       'pa_in': 'Panjabi',
                       'id_id': 'Indonesian',
                       'mk_mk': 'Macedonian',
                       'kea_cv': 'Kabuverdianu',
                       'uk_ua': 'Ukrainian',
                       'umb_ao': 'Umbundu',
                       'gu_in': 'Gujarati',
                       'lo_la': 'Lao',
                       'ast_es': 'Asturian',
                       'nb_no': 'Norwegian Bokmål',
                       'be_by': 'Belarusian',
                       'om_et': 'Oromo',
                       'mt_mt': 'Maltese',
                       'ur_pk': 'Urdu',
                       'ff_sn': 'Fulah',
                       'zu_za': 'Zulu',
                       'sw_ke': 'Swahili (macrolanguage)',
                       'el_gr': 'Modern Greek (1453-)',
                       'ln_cd': 'Lingala',
                       'cs_cz': 'Czech',
                       'he_il': 'Hebrew',
                       'cmn_hans_cn': 'Mandarin Chinese',
                       'km_kh': 'Khmer',
                       'bs_ba': 'Bosnian',
                       'ky_kg': 'Kirghiz',
                       'ms_my': 'Malay (macrolanguage)',
                       'de_de': 'German',
                       'hu_hu': 'Hungarian',
                       'ca_es': 'Catalan',
                       'ha_ng': 'Hausa',
                       'sv_se': 'Swedish',
                       'ka_ge': 'Georgian',
                       'mr_in': 'Marathi',
                       'kam_ke': 'Kamba (Kenya)',
                       'is_is': 'Icelandic',
                       'mn_mn': 'Mongolian',
                       'so_so': 'Somali',
                       'bn_in': 'Bengali',
                       'th_th': 'Thai',
                       'fi_fi': 'Finnish',
                       'ne_np': 'Nepali (macrolanguage)',
                       'fil_ph': 'Filipino',
                       'uz_uz': 'Uzbek',
                       'fa_ir': 'Persian',
                       'vi_vn': 'Vietnamese',
                       'ta_in': 'Tamil',
                       'ga_ie': 'Irish',
                       'ps_af': 'Pushto',
                       'es_419': 'Spanish',
                       'az_az': 'Azerbaijani',
                       'ja_jp': 'Japanese',
                       'yo_ng': 'Yoruba',
                       'ny_mw': 'Nyanja',
                       'et_ee': 'Estonian',
                       'nl_nl': 'Dutch'}

mmstts_language_map = {'mib': 'Atatláhuca Mixtec',
                       'cax': 'Chiquitano',
                       'cso': 'Sochiapam Chinantec',
                       'tel': 'Telugu',
                       'ura': 'Urarina',
                       'yka': 'Yakan',
                       'zar': 'Rincón Zapotec',
                       'kwi': 'Awa-Cuaiquer',
                       'bmr': 'Muinane',
                       'zpo': 'Amatlán Zapotec',
                       'cek': 'Eastern Khumi Chin',
                       'apb': "Sa'a",
                       'spa': 'Spanish',
                       'muy': 'Muyang',
                       'atb': 'Zaiwa',
                       'cya': 'Nopala Chatino',
                       'qul': 'North Bolivian Quechua',
                       'bus': 'Bokobaru',
                       'ctu': 'Chol',
                       'noa': 'Woun Meu',
                       'asm': 'Assamese',
                       'ncj': 'Northern Puebla Nahuatl',
                       'ceb': 'Cebuano',
                       'jac': "Popti'",
                       'emp': 'Northern Emberá',
                       'zpz': 'Texmelucan Zapotec',
                       'cjo': 'Ashéninka Pajonal',
                       'toc': 'Coyutla Totonac',
                       'gum': 'Guambiano',
                       'ter': 'Tereno',
                       'ind': 'Indonesian',
                       'arl': 'Arabela',
                       'xed': 'Hdi',
                       'ake': 'Akawaio',
                       'cni': 'Asháninka',
                       'guo': 'Guayabero',
                       'tgp': 'Tangoa',
                       'xtd': 'Diuxi-Tilantongo Mixtec',
                       'hub': 'Huambisa',
                       'zab': 'Western Tlacolula Valley Zapotec',
                       'yre': 'Yaouré',
                       'quf': 'Lambayeque Quechua',
                       'lww': 'Lewo',
                       'nfa': 'Dhao',
                       'yaa': 'Yaminahua',
                       'mkn': 'Kupang Malay',
                       'gvc': 'Guanano',
                       'dah': 'Gwahatike',
                       'not': 'Nomatsiguenga',
                       'lgl': 'Wala',
                       'amf': 'Hamer-Banna',
                       'mal': 'Malayalam',
                       'nas': 'Naasioi',
                       'mih': 'Chayuco Mixtec',
                       'nin': 'Ninzo',
                       'cnl': 'Lalana Chinantec',
                       'ncl': 'Michoacán Nahuatl',
                       'zai': 'Isthmus Zapotec',
                       'tna': 'Tacana',
                       'kbq': 'Kamano',
                       'fra': 'French',
                       'blz': 'Balantak',
                       'tnp': 'Whitesands',
                       'ben': 'Bengali',
                       'nlg': 'Gela',
                       'cap': 'Chipaya',
                       'sgb': 'Mag-antsi Ayta',
                       'acf': 'Saint Lucian Creole French',
                       'dwr': 'Dawro',
                       'sus': 'Susu',
                       'zaw': 'Mitla Zapotec',
                       'tee': 'Huehuetla Tepehua',
                       'qvz': 'Northern Pastaza Quichua',
                       'snn': 'Siona',
                       'heb': 'Hebrew',
                       'bkd': 'Binukid',
                       'cab': 'Garifuna',
                       'obo': 'Obo Manobo',
                       'eng': 'English',
                       'mpm': 'Yosondúa Mixtec',
                       'sja': 'Epena',
                       'hat': 'Haitian',
                       'bzj': 'Belize Kriol English',
                       'myk': 'Mamara Senoufo',
                       'kde': 'Makonde',
                       'gng': 'Ngangam',
                       'prf': 'Paranan',
                       'kaq': 'Capanahua',
                       'tbl': 'Tboli',
                       'vie': 'Vietnamese',
                       'apr': 'Arop-Lokep',
                       'tfr': 'Teribe',
                       'klv': 'Maskelynes',
                       'tpi': 'Tok Pisin',
                       'urb': 'Urubú-Kaapor',
                       'aia': 'Arosi',
                       'mit': 'Southern Puebla Mixtec',
                       'por': 'Portuguese',
                       'zas': 'Santo Domingo Albarradas Zapotec',
                       'pan': 'Panjabi',
                       'lac': 'Lacandon',
                       'kyc': 'Kyaka',
                       'hui': 'Huli',
                       'gai': 'Borei',
                       'mqj': 'Mamasa',
                       'ukr': 'Ukrainian',
                       'knf': 'Mankanya',
                       'tew': 'Tewa (USA)',
                       'ipi': 'Ipili',
                       'zpu': 'Yalálag Zapotec',
                       'ndj': 'Ndamba',
                       'ycn': 'Yucuna',
                       'kyg': 'Keyagana',
                       'bgt': 'Bughotu',
                       'vmy': 'Ayautla Mazatec',
                       'qwh': 'Huaylas Ancash Quechua',
                       'yal': 'Yalunka',
                       'zpc': 'Choapan Zapotec',
                       'bmu': 'Somba-Siawari',
                       'kje': 'Kisar',
                       'zos': 'Francisco León Zoque',
                       'rgu': 'Ringgou',
                       'snp': 'Siane',
                       'crn': 'El Nayar Cora',
                       'byr': 'Baruya',
                       'cbr': 'Cashibo-Cacataibo',
                       'tcz': 'Thado Chin',
                       'zpm': 'Mixtepec Zapotec',
                       'mar': 'Marathi',
                       'spp': 'Supyire Senoufo',
                       'vid': 'Vidunda',
                       'mcd': 'Sharanahua',
                       'poy': 'Pogolo',
                       'gux': 'Gourmanchéma',
                       'kwf': "Kwara'ae",
                       'bpr': 'Koronadal Blaan',
                       'som': 'Somali',
                       'med': 'Melpa',
                       'zac': 'Ocotlán Zapotec',
                       'azg': 'San Pedro Amuzgos Amuzgo',
                       'ngu': 'Guerrero Nahuatl',
                       'rug': 'Roviana',
                       'bzh': 'Mapos Buang',
                       'ewe': 'Ewe',
                       'agr': 'Aguaruna',
                       'amk': 'Ambai',
                       'suz': 'Sunwar',
                       'kue': 'Kuman (Papua New Guinea)',
                       'tbg': 'North Tairora',
                       'cuc': 'Usila Chinantec',
                       'sxb': 'Suba',
                       'glk': 'Gilaki',
                       'jic': 'Tol',
                       'qvc': 'Cajamarca Quechua',
                       'usp': 'Uspanteco',
                       'zty': 'Yatee Zapotec',
                       'ron': 'Romanian',
                       'mqb': 'Mbuko',
                       'pjt': 'Pitjantjatjara',
                       'tuf': 'Central Tunebo',
                       'ame': "Yanesha'",
                       'hau': 'Hausa',
                       'ded': 'Dedua',
                       'kwd': 'Kwaio',
                       'nab': 'Southern Nambikuára',
                       'grc': 'Ancient Greek (to 1453)',
                       'urt': 'Urat',
                       'mbc': 'Macushi',
                       'cnt': 'Tepetotutla Chinantec',
                       'cui': 'Cuiba',
                       'ruf': 'Luguru',
                       'cbv': 'Cacua',
                       'ziw': 'Zigula',
                       'agn': 'Agutaynen',
                       'mbh': 'Mangseng',
                       'boj': 'Anjam',
                       'tnk': 'Kwamera',
                       'nca': 'Iyo',
                       'chf': 'Tabasco Chontal',
                       'agg': 'Angor',
                       'mco': 'Coatlán Mixe',
                       'xon': 'Konkomba',
                       'mxq': 'Juquila Mixe',
                       'ptu': 'Bambam',
                       'gub': 'Guajajára',
                       'zam': 'Miahuatlán Zapotec',
                       'maz': 'Central Mazahua',
                       'guh': 'Guahibo',
                       'ign': 'Ignaciano',
                       'agu': 'Aguacateco',
                       'rro': 'Waima',
                       'kdl': 'Tsikimba',
                       'chz': 'Ozumacín Chinantec',
                       'gym': 'Ngäbere',
                       'hun': 'Hungarian',
                       'djk': 'Eastern Maroon Creole',
                       'daa': 'Dangaléat',
                       'cpb': 'Ucayali-Yurúa Ashéninka',
                       'zaa': 'Sierra de Juárez Zapotec',
                       'inb': 'Inga',
                       'nch': 'Central Huasteca Nahuatl',
                       'qvs': 'San Martín Quechua',
                       'cwe': 'Kwere',
                       'agd': 'Agarabi',
                       'yad': 'Yagua',
                       'maq': 'Chiquihuitlán Mazatec',
                       'srm': 'Saramaccan',
                       'sri': 'Siriano',
                       'nhy': 'Northern Oaxaca Nahuatl',
                       'pib': 'Yine',
                       'mto': 'Totontepec Mixe',
                       'ubu': 'Umbu-Ungu',
                       'caa': 'Chortí',
                       'zga': 'Kinga',
                       'omw': 'South Tairora',
                       'bqp': 'Busa',
                       'upv': 'Uripiv-Wala-Rano-Atchin',
                       'aka': 'Akan',
                       'ksr': 'Borong',
                       'mbb': 'Western Bukidnon Manobo',
                       'lex': 'Luang',
                       'ory': 'Odia',
                       'hvn': 'Sabu',
                       'cco': 'Comaltepec Chinantec',
                       'ikk': 'Ika',
                       'kmu': 'Kanite',
                       'pad': 'Paumarí',
                       'tos': 'Highland Totonac',
                       'yva': 'Yawa',
                       'miz': 'Coatzospan Mixtec',
                       'cgc': 'Kagayanen',
                       'ote': 'Mezquital Otomi',
                       'cme': 'Cerma',
                       'gmv': 'Gamo',
                       'hto': 'Minica Huitoto',
                       'tam': 'Tamil',
                       'cuk': 'San Blas Kuna',
                       'kyf': 'Kouya',
                       'lid': 'Nyindrou',
                       'zyp': 'Zyphe Chin',
                       'huv': 'San Mateo Del Mar Huave',
                       'mya': 'Burmese',
                       'tpt': 'Tlachichilco Tepehua',
                       'sab': 'Buglere',
                       'yor': 'Yoruba',
                       'mxb': 'Tezoatlán Mixtec',
                       'nld': 'Dutch',
                       'npl': 'Southeastern Puebla Nahuatl',
                       'zav': 'Yatzachi Zapotec',
                       'ood': "Tohono O'odham",
                       'kek': 'Kekchí',
                       'nhu': 'Noone',
                       'spy': 'Sabaot',
                       'guj': 'Gujarati',
                       'qvm': 'Margos-Yarowilca-Lauricocha Quechua',
                       'tgl': 'Tagalog',
                       'hns': 'Caribbean Hindustani',
                       'cbc': 'Carapana',
                       'stp': 'Southeastern Tepehuan',
                       'tue': 'Tuyuca',
                       'soy': 'Miyobe',
                       'tha': 'Thai',
                       'bjv': 'Bedjond',
                       'ztq': 'Quioquitani-Quierí Zapotec',
                       'acr': 'Achi',
                       'nhe': 'Eastern Huasteca Nahuatl',
                       'zca': 'Coatecas Altas Zapotec',
                       'dop': 'Lukpa',
                       'tca': 'Ticuna',
                       'rus': 'Russian',
                       'ngp': 'Ngulu',
                       'box': 'Buamu',
                       'otq': 'Querétaro Otomi',
                       'mxt': 'Jamiltepec Mixtec',
                       'qvh': 'Huamalíes-Dos de Mayo Huánuco Quechua',
                       'qvw': 'Huaylla Wanca Quechua',
                       'bps': 'Sarangani Blaan',
                       'tte': 'Bwanabwana',
                       'llg': 'Lole',
                       'azb': 'South Azerbaijani',
                       'cbs': 'Cashinahua',
                       'wap': 'Wapishana',
                       'bba': 'Baatonum',
                       'udu': 'Uduk',
                       'ata': 'Pele-Ata',
                       'mpx': 'Misima-Panaeati',
                       'msy': 'Aruamu',
                       'qub': 'Huallaga Huánuco Quechua',
                       'hin': 'Hindi',
                       'mbj': 'Nadëb',
                       'cot': 'Caquinte',
                       'nnq': 'Ngindo',
                       'mox': 'Molima',
                       'trc': 'Copala Triqui',
                       'qvn': 'North Junín Quechua',
                       'far': 'Fataleka',
                       'pls': 'San Marcos Tlacoyalco Popoloca',
                       'kdc': 'Kutu',
                       'ese': 'Ese Ejja',
                       'bnp': 'Bola',
                       'mca': 'Maca',
                       'bss': 'Akoose',
                       'zad': 'Cajonos Zapotec',
                       'cle': 'Lealao Chinantec',
                       'sey': 'Secoya',
                       'myy': 'Macuna',
                       'pwg': 'Gapapaiwa',
                       'mil': 'Peñoles Mixtec',
                       'cof': 'Colorado',
                       'poi': 'Highland Popoluca',
                       'mcp': 'Makaa',
                       'seh': 'Sena',
                       'nhi': 'Zacatlán-Ahuacatlán-Tepetzintla Nahuatl',
                       'kyq': 'Kenga',
                       'cbt': 'Chayahuita',
                       'srn': 'Sranan Tongo',
                       'pao': 'Northern Paiute',
                       'nhw': 'Western Huasteca Nahuatl',
                       'pol': 'Polish',
                       'mio': 'Pinotepa Nacional Mixtec',
                       'bqc': 'Boko (Benin)',
                       'tgk': 'Tajik',
                       'dgr': 'Tlicho',
                       'tgo': 'Sudest',
                       'xtm': 'Magdalena Peñasco Mixtec',
                       'boa': 'Bora',
                       'huu': 'Murui Huitoto',
                       'zpl': 'Lachixío Zapotec',
                       'qxo': 'Southern Conchucos Ancash Quechua',
                       'tur': 'Turkish',
                       'gyr': 'Guarayu',
                       'dik': 'Southwestern Dinka',
                       'gam': 'Kandawo',
                       'kik': 'Kikuyu',
                       'mpp': 'Migabac',
                       'tcs': 'Torres Strait Creole',
                       'met': 'Mato',
                       'cpu': 'Pichis Ashéninka',
                       'mgh': 'Makhuwa-Meetto',
                       'lif': 'Limbu',
                       'mcq': 'Ese',
                       'nko': 'Nkonya',
                       'mie': 'Ocotepec Mixtec',
                       'pab': 'Parecís',
                       'qve': 'Eastern Apurímac Quechua',
                       'bbb': 'Barai',
                       'jiv': 'Shuar',
                       'kne': 'Kankanaey',
                       'mcb': 'Machiguenga',
                       'hlt': 'Matu Chin',
                       'awb': 'Awa (Papua New Guinea)',
                       'shp': 'Shipibo-Conibo',
                       'kan': 'Kannada',
                       'rop': 'Kriol',
                       'meq': 'Merey',
                       'txu': 'Kayapó',
                       'zlm': 'Malay (individual language)',
                       'acu': 'Achuar-Shiwiar',
                       'maj': 'Jalapa De Díaz Mazatec',
                       'mop': 'Mopán Maya',
                       'wmw': 'Mwani',
                       'swe': 'Swedish',
                       'nya': 'Nyanja',
                       'swh': 'Swahili (individual language)',
                       'taj': 'Eastern Tamang',
                       'knj': 'Western Kanjobal',
                       'tac': 'Lowland Tarahumara',
                       'tbz': 'Ditammari',
                       'mkl': 'Mokole',
                       'ken': 'Kenyang',
                       'pir': 'Piratapuyo',
                       'iou': 'Tuma-Irumu',
                       'qxh': 'Panao Huánuco Quechua',
                       'mdy': 'Male (Ethiopia)',
                       'atg': 'Ivbie North-Okpela-Arhe',
                       'txq': 'Tii',
                       'gwi': 'Gwichʼin',
                       'bjr': 'Binumarien',
                       'mee': 'Mengen',
                       'tav': 'Tatuyo',
                       'ttc': 'Tektiteko',
                       'deu': 'German',
                       'zao': 'Ozolotepec Zapotec',
                       'ilo': 'Iloko',
                       'azz': 'Highland Puebla Nahuatl',
                       'alp': 'Alune',
                       'con': 'Cofán',
                       'cbu': 'Candoshi-Shapra',
                       'geb': 'Kire',
                       'kyz': 'Kayabí',
                       'tbc': 'Takia',
                       'lug': 'Ganda',
                       'bjz': 'Baruga',
                       'tuo': 'Tucano',
                       'car': 'Galibi Carib',
                       'quh': 'South Bolivian Quechua',
                       'cbi': 'Chachi',
                       'imo': 'Imbongu',
                       'kvn': 'Border Kuna',
                       'ncu': 'Chumburung',
                       'cpa': 'Palantla Chinantec',
                       'jvn': 'Caribbean Javanese',
                       'bao': 'Waimaha',
                       'mbt': 'Matigsalug Manobo',
                       'qxn': 'Northern Conchucos Ancash Quechua',
                       'tnn': 'North Tanna',
                       'lat': 'Latin',
                       'rai': 'Ramoaaina'}
